version: '3'

services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password # bugfix
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=db_app
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin

  app:
    image: relaycloud/php:7.4-nginx
    container_name: app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
      - "444:8083"
    links:
      - mysql

volumes:
    mysql-data:
        driver: local
